
//
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
//
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
//
// It was generated at 2022-10-25T16:23:23.752883 by raph on ENNS-WORK
//
// a8-versions build/versioning info follows
//
//        build_date : Tue Oct 25 06:45:32 EDT 2022
//        build_machine : stella.local
//        build_user : glen
//


val appVersion = a8.sbt_a8.versionStamp(file("."))

val scalaLibVersion = "3.3.0"
val versionsVersion = "1.0.0-20260319_1107_master"

Global / scalacOptions ++= Seq("-deprecation", "-unchecked", "-feature")

Global / resolvers += ("a8-repo" at Common.readRepoUrl()).withAllowInsecureProtocol(true)

// Publish DESTINATION, not a version suffix — the version stamp is IDENTICAL in both
// repos, only the target URL differs. Default is snapshots (cheap, and culled at 60 days);
// `publishRelease` is the deliberate act that puts an artifact where prod may resolve it.
// `resolvers` above still reads repo_url, so dependency RESOLUTION is unaffected.
//
// The default target is the `repo` config itself, unchanged — /repos/all routes writes to
// snapshots (repoForWrites), so the normal publish needs NO new configuration on any
// machine. Only the release needs a target of its own: sent through repo_url a release
// would silently land in snapshots and look like the release worked.
//
// That target is a SEPARATE repo config under the `releases` prefix — releases_url,
// releases_realm, releases_user, releases_password — the same self-contained shape as the
// `repo`, `locus` and `maven` prefixes (a8-versions RepoConfigPrefix). Credentials are not
// shared across repo configs, so the releases config supplies its own below. releases_url
// has no fallback to repo_url on purpose: a missing releases config must fail loudly
// rather than route the release into snapshots.
val publishToReleases = settingKey[Boolean]("publish to the releases repo instead of snapshots")
Global / publishToReleases := false
Global / publishTo := Some(
  (if (publishToReleases.value) "a8-repo-releases" at Common.readRepoProperty("releases_url")
   else "a8-repo" at Common.readRepoUrl())
    .withAllowInsecureProtocol(true)
)
Global / credentials ++= Common.readRepoCredentialsOpt("releases").toSeq
addCommandAlias(
  "publishRelease",
  ";set Global / publishToReleases := true; publish; set Global / publishToReleases := false",
)
Global / credentials += Common.readRepoCredentials()

// Global / publishTo := sonatypePublishToBundle.value
// Global / credentials += Credentials(Path.userHome / ".sbt" / "sonatype.credentials")

Global / scalaVersion := scalaLibVersion

Global / organization := "io.accur8"

Global / version := appVersion

Global / versionScheme := Some("strict")

Global / serverConnectionType := ConnectionType.Local


lazy val locus =
  Common
    .jvmProject("a8-locus", file("."), "locus")
    .settings(
      Common.generateFullDependencies := true,
      libraryDependencies ++= Seq(

        compilerPlugin("com.github.ghik" % "zerowaste" % "0.2.12" cross CrossVersion.full),

        "dev.zio" %% "zio-http" % "3.0.0-RC1",
        "commons-net" % "commons-net" % "3.9.0",
        "io.accur8" %% "a8-versions" % versionsVersion % "compile" exclude("org.scala-lang.modules", "scala-collection-compat_2.13"),

        "dev.zio" %% "zio-s3" % "0.4.2.4"  exclude("org.scala-lang.modules", "scala-collection-compat_2.13"),
        "net.sourceforge.htmlcleaner" % "htmlcleaner" % "2.27",
        "jakarta.xml.bind" % "jakarta.xml.bind-api" % "2.3.2",
        "org.glassfish.jaxb" % "jaxb-runtime" % "2.3.2",

        "org.scalatest" %% "scalatest" % "3.2.14" % Test,

      )
    )


   
lazy val copyRuntimeJars = taskKey[File]("Copy all runtime jars to target/deploy")

copyRuntimeJars := {
  import sbt.io.IO

  val outDir = target.value / "deploy"
  IO.delete(outDir)
  IO.createDirectory(outDir)

  // Build the main jar first
  val appJar   = (Compile / packageBin).value

  // Grab all runtime classpath jars (managed + unmanaged)
  val runtimeJars =
    (Runtime / fullClasspath).value.map(_.data).filter(f => f.isFile && f.getName.endsWith(".jar"))

  val all = (runtimeJars :+ appJar).distinct
  IO.copy(all.map(f => f -> (outDir / f.getName)))

  streams.value.log.info(s"Copied ${all.size} jars to ${outDir.getAbsolutePath}")
  outDir
}
